Feat/subscribe button
mail3protocol/mail3-web-client pull request #218
Opened 2022-11-17 03:14 UTC by shadow2kk

2022-11-18 01:44 UTC, LucasM19 approved these changes

2022-11-22 05:58 UTC, LucasM19 approved these changes

2022-11-22 07:03 UTC, Codemasker requested changes

2022-11-22 07:03 UTC, Codemasker commented on packages/ui/src/theme/index.tsx
> +        bg: '',
What's the use here?

2022-11-22 07:03 UTC, Codemasker commented on packages/ui/src/SubscribeButton/index.tsx
> +        src={`${host}/subscribe/button?uuid=${uuid}
This `src` can use `useMemo`, Because has many `JSON.stringify`

2022-11-22 08:23 UTC, Vibes-INS approved these changes

2022-11-22 08:23 UTC, Codemasker approved these changes

2022-11-23 00:52 UTC, merged