Feat/subscribe claim animate
mail3protocol/mail3-web-client pull request #234
Opened 2022-11-30 15:16 UTC by shadow2kk

2022-12-02 09:38 UTC, LucasM19 approved these changes

2022-12-02 09:53 UTC, Codemasker requested changes

2022-12-02 09:53 UTC, Codemasker commented on apps/app/components/NotificationSwitch/BaseSwitch.tsx
> +  inactiveBg?: string
You should use `bg` directly. Because `bg` in `FlexProps` can cover original `bg`.

2022-12-05 06:16 UTC, Codemasker approved these changes

2022-12-05 06:18 UTC, ghcoldsnap approved these changes

2022-12-05 06:31 UTC, merged