feat: add Christmas avatar and refactor avatar api
mail3protocol/mail3-web-client pull request #241
Opened 2022-12-16 07:44 UTC by shadow2kk

2022-12-19 08:42 UTC, LucasM19 approved these changes

2022-12-19 08:54 UTC, Codemasker requested changes

2022-12-19 08:54 UTC, Codemasker commented on apps/app/components/Settings/SettingAvatar.tsx
> +  const [, setAvatars] = useAtom(avatarsAtom)
`useUpdateAtom` should be used here

2022-12-19 08:54 UTC, Codemasker commented on apps/home/constants/env.ts
> +export const HOME_URL = process.env.NEXT_PUBLIC_HOME_URL || 'https://mail3.me'
Why not use `location.origin` directly here. if it is in the `Nodejs`, You can use the `req.headers.host`

2022-12-19 08:54 UTC, Codemasker commented on apps/home/pages/api/avatar/[address].ts
> +const DEFAULT_AVATAR_SRC =
It should be written in the environment variable.

2022-12-19 08:54 UTC, Codemasker commented on apps/home/pages/api/avatar/[address].ts
> +  const defaultAvatarUrl = `${HOME_URL}/avatar/${currentDefaultAvatar}.png`
If the default avatar is in the public directory, you can directly request `/public/avatar/normal.png`

2022-12-19 08:54 UTC, Codemasker commented on packages/ui/src/Avatar/index.tsx
> +const currentAvatarType = DefaultAvatarType.Christmas
It should be controlled by environmental variables here.

2022-12-19 09:02 UTC, Codemasker requested changes

2022-12-19 09:02 UTC, Codemasker commented on packages/ui/src/Avatar/index.tsx
> +const getImageSrc = (img: string | { src: string }) => {
Just a line:
```suggestion
const getImageSrc = (img: string | { src: string }) => typeof img === 'string' ? img : img.src
```

2022-12-19 09:34 UTC, yuche approved these changes

2022-12-20 03:38 UTC, Codemasker requested changes

2022-12-20 03:38 UTC, Codemasker commented on apps/home/pages/api/avatar/[address].ts
> +// Constant will never change
```suggestion
// Solve problems left over by history
```

2022-12-20 03:47 UTC, merged