Feat/co authors
mail3protocol/mail3-web-client pull request #277
Opened 2023-01-31 08:29 UTC by shadow2kk

2023-02-02 06:44 UTC, Codemasker requested changes

2023-02-02 06:44 UTC, Codemasker commented on apps/community/src/pages/co-authors.tsx
> +        {t('Unbind')}
没有这个 key 吧

2023-02-02 06:44 UTC, Codemasker commented on apps/community/src/pages/co-authors.tsx
> +    if (address) {
可以这样，减少代码缩进
```ts
if (!address) return
// do something......
```

2023-02-02 06:44 UTC, Codemasker commented on apps/community/src/pages/co-authors.tsx
> +                        if (isAdmin && isAdminRemote) {
可以用 `Array.filter`

2023-02-02 06:44 UTC, Codemasker commented on apps/community/src/pages/co-authors.tsx
> +              'COMMUNITY_COLLABORATORS_ADDRESS_INVALID'
这个 `ErrorCode` 应该写在 `apps/community/src/api/ErrorCode.ts`

2023-02-02 06:44 UTC, Codemasker commented on apps/community/src/pages/co-authors.tsx
> +            error?.response?.data.reason === 'ADDRESS_INVALID'
这个也是应该写在 `apps/community/src/api/ErrorCode.ts`

2023-02-02 06:44 UTC, Codemasker commented on apps/community/src/pages/co-authors.tsx
> +            error?.response?.data.reason === 'ADDRESS_INVALID'
这个也是应该写在 `apps/community/src/api/ErrorCode.ts`

2023-02-13 07:08 UTC, LucasM19 approved these changes

2023-02-13 07:14 UTC, Codemasker approved these changes

2023-02-13 07:14 UTC, Codemasker commented on apps/community/src/pages/co-authors.tsx
> +                  border="1px solid #F2F2F2"
border="1px solid" borderColor="lineColor"

2023-02-13 07:14 UTC, Codemasker commented on apps/community/src/pages/co-authors.tsx
> +    // clear old value
这个注释不需要

2023-02-13 07:24 UTC, ghcoldsnap approved these changes

2023-02-13 07:39 UTC, merged