Feat/editor modify
mail3protocol/mail3-web-client pull request #344
Opened 2023-03-30 08:19 UTC by shadow2kk

2023-03-31 09:41 UTC, LucasM19 approved these changes

2023-04-03 07:33 UTC, ghcoldsnap approved these changes

2023-04-03 07:37 UTC, Codemasker requested changes

2023-04-03 07:37 UTC, Codemasker commented on apps/community/src/components/NewMessagePageComponents/SendButton.tsx
> +  const pStrList: string[] = []
这里变量名用 `paragraphs` 意义比较明确
```suggestion
  const paragraphs: string[] = []
```

2023-04-03 07:41 UTC, Codemasker approved these changes

2023-04-03 07:41 UTC, merged